### ISSUE TITLE
Focusable buttons

### ISSUE THREAD

**Issue by MrStahlfelge** [raeleus/Shadow-Walker-UI#1]
Hi, just looked at the code because of the focusable buttons. As far as I see is the only new feature the support for defining a dedicated drawable for the Actor that currently the keyboard focus is set to?

Perhaps you might want to use my tiny lib for handling keyboard focus: https://github.com/MrStahlfelge/gdx-controllerutils/wiki/Button-operable-Scene2d - you could remove the focusIndex var and it will still work if you rearrange the buttons. Would be glad to link this as an example project then!

Btw, I think it would be good if you add direct links to your website from the GitHub repos. :-)

**Comment by raeleus** [comment]
I am familiar with your work and it was actually the inspiration to make this example when I learned about the new feature. The goal of this project was to highlight how someone might do it with vanilla LibGDX, but your solution is much cleaner. What I'll likely do is branch the project and have two different releases to inspect. Thanks for the suggestion!

With ButtonStyle.focused and ButtonStyle.checkFocused being a thing now, do you think you can modify your library to support these fields? I like the idea of having different drawables for mouse over vs keyboard focus.

**Comment by raeleus** [comment]
You weren't kidding: it was pretty easy. See https://github.com/raeleus/Shadow-Walker-UI/tree/ControllerMenuStage

**Comment by MrStahlfelge** [comment]
Great. :-)

I would expect it to respect the different drawables for mouse and keyboard right now. Is this the case?

**Comment by raeleus** [comment]
Using my implementation, it does work. Using ControllerMenuStage, it only activates ButtonStyle.over so it's the same drawable for mouse over and keyboard focus. Unless I missed something... Thanks for your help.

**Comment by MrStahlfelge** [comment]
This is caused by ControllerMenuStage sending enter and exit events to the Actor, which is good for <= 1.9.8 and not so good for 1.9.9. I will add a setter to change this behaviour in a few hours. If you want to try in the meantime, you can also change this by overriding either onFocusGained and onFocusLost methods to not call fireEventOnActor, or by overriding fireEventOnActor method to not deliver enter/exit events.

**Comment by MrStahlfelge** [comment]
I pushed a new version and tried with your project on the ControllerMenuStage branch and the following changes:
* Reverted skin change
* cuVersion 0.1.3-SNAPSHOT
* stage.setSendMouseOverEvents(false);

This works better, an annoyance is that Button favors the over drawable over the focus drawable which is not correct in this case but might be correct in other situations. Best solution was adding a focusedOver drawable, but as we can't do that second best approach is overriding the button's isOver() method to return false when the button is focused.

And thanks for the link, added one as well. :)

**Comment by raeleus** [comment]
That works really well. Thank you so much for doing that.

**Comment by MrStahlfelge** [comment]
You are very welcome! By the way, if you like, I would appreciate to see you on the libGDX discord! https://discord.gg/6pgDK9F
